/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        "on-background": "#f3f0ef",
        surface: "#131313",
        "on-surface": "#f3f0ef",
        "surface-variant": "#393939",
        "on-surface-variant": "#c9c6c1",
        outline: "#8d7168",
        "outline-variant": "#474743",
        primary: "#ff6b35", // Zesty Orange
        "on-primary": "#ffffff",
        "primary-container": "#ff6b35",
        "on-primary-container": "#5f1900",
        secondary: "#c9c6c1",
        "on-secondary": "#1c1b1b",
        "secondary-container": "#474743",
        "on-secondary-container": "#e5e2dc",
        tertiary: "#61de8a", // Fresh Basil Green
        "on-tertiary": "#003a1a",
        "tertiary-container": "#005228",
        "on-tertiary-container": "#7efba4",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#212121",
        "surface-container-high": "#2b2b2b",
        "surface-container-highest": "#363636",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdbd0",
        "on-primary-fixed": "#390c00",
        "primary-fixed-dim": "#ffb59d",
        "secondary-fixed": "#e5e2dc",
        "secondary-fixed-dim": "#c9c6c1",
        "on-secondary-fixed": "#1c1c18",
        "on-secondary-fixed-variant": "#474743",
        "tertiary-fixed": "#7efba4",
        "tertiary-fixed-dim": "#61de8a",
        "on-tertiary-fixed": "#00210c",
        "on-tertiary-fixed-variant": "#005228",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#ffb59d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
